## Numpy

### numpy 기본 1. 다차원 배열 만들기

In [1]:
# numpy 임포트
import numpy as np

In [2]:
# 1차원 배열 생성하기
numpy_array1 = np.array([1,2,3,4])
numpy_array1

array([1, 2, 3, 4])

In [3]:
# 2차원 배열 생성하기
numpy_array2 = np.array([[1,2,3,4],[11,12,13,14]])
numpy_array2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [4]:
# 3차원 배열 생성하기
numpy_array3 = np.array([ [[1,2,3,4],[11,12,13,14]],
                [[21,22,23,24],[31,32,33,34]] ])
numpy_array3

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [31, 32, 33, 34]]])

In [5]:
# 배열의 모양 보기
print(numpy_array1.shape)
print(numpy_array2.shape)
print(numpy_array3.shape)

(4,)
(2, 4)
(2, 2, 4)


In [6]:
z1 = np.zeros([4])    # 0 으로 채운 배열 만들기
o2 = np.ones([3,4])   # 1 로 채운 배열 만들기
r2 = np.random.randn(2,3)   # 랜덤한 숫자 배열 만들기

In [7]:
z1, o2, r2

(array([0., 0., 0., 0.]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[ 0.96710826, -0.20684232, -0.5635993 ],
        [ 0.54286942, -2.51830956,  0.14317771]]))

In [8]:
# 배열의 모양 보기
print(z1.shape)
print(o2.shape)
print(r2.shape)

(4,)
(3, 4)
(2, 3)


In [9]:
# 무척 큰 4차원 배열 생성해보기
r4 = np.random.randn(2,2,4,5).round(3)
r4

array([[[[ 1.458, -0.319, -0.701,  0.161,  0.478],
         [-0.084, -0.345,  1.678,  1.159,  0.26 ],
         [-0.897, -1.585,  1.069,  1.171, -0.257],
         [ 0.407,  0.214, -1.648, -0.041, -0.209]],

        [[ 2.167, -0.04 , -0.525, -0.709,  0.436],
         [-1.205, -1.59 , -0.416,  1.565,  0.673],
         [ 0.686, -1.144, -0.075, -0.028,  0.307],
         [ 1.137,  0.574,  0.193, -0.621, -1.874]]],


       [[[-0.775, -0.585,  0.059, -1.419,  0.161],
         [ 0.347,  0.92 ,  1.636, -0.994,  0.395],
         [ 0.08 , -0.811,  0.436, -1.083,  1.084],
         [ 0.621, -0.177,  0.292, -2.359,  1.672]],

        [[ 0.273, -0.082, -0.008, -2.05 ,  0.305],
         [ 0.134,  0.522, -0.116,  0.952,  0.572],
         [-0.655,  0.259, -0.934,  0.557,  0.   ],
         [-0.117,  0.869,  1.511,  0.262, -0.412]]]])

### numpy 기본 2. Indexing과 Slicing

In [10]:
# r4 배열에서, [두번째][첫번째] 접근해서 가져오기
r4[1][0]

array([[-0.775, -0.585,  0.059, -1.419,  0.161],
       [ 0.347,  0.92 ,  1.636, -0.994,  0.395],
       [ 0.08 , -0.811,  0.436, -1.083,  1.084],
       [ 0.621, -0.177,  0.292, -2.359,  1.672]])

In [11]:
r4[1][0][2]

array([ 0.08 , -0.811,  0.436, -1.083,  1.084])

In [12]:
r4[1][0][2][4]

1.084

In [13]:
r4[1,0,2,4]   # 대괄호 대신 쉼표 , 도 차원 접근이 가능

1.084

In [14]:
r4[1][0][2][0:4:2]

array([0.08 , 0.436])

In [15]:
r4[1][0][1:4:2]

array([[ 0.347,  0.92 ,  1.636, -0.994,  0.395],
       [ 0.621, -0.177,  0.292, -2.359,  1.672]])

In [16]:
# Indexing과 Slicing 같이 적용하기
r4[1][0][1:4:2][1][3:]

array([-2.359,  1.672])

In [17]:
r4[1,0][1:4:2][1,3:]   # 모두 다 짬뽕!!

array([-2.359,  1.672])

### numpy 기본 3. 배열 간 연산, Broadcasting, Aggregation

In [18]:
arr = np.array([[1,2,3,4],[10,11,12,13]])
arr

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [19]:
arr + arr    # 배열끼리 연산하기 (＋－*/ 모두 가능)

array([[ 2,  4,  6,  8],
       [20, 22, 24, 26]])

In [20]:
arr + 20     # 덧셈 브로드캐스팅

array([[21, 22, 23, 24],
       [30, 31, 32, 33]])

In [21]:
arr * 100    # 곱셈 브로드캐스팅

array([[ 100,  200,  300,  400],
       [1000, 1100, 1200, 1300]])

In [23]:
# 배열 전체의 덧셈, 평균, 곱셈, 최댓값, 최솟값
arr.sum(), arr.mean(), arr.prod(), arr.max(), arr.min()

(56, 7.0, 411840, 13, 1)

In [24]:
arr[1]

array([10, 11, 12, 13])

In [25]:
# 배열에서의 최대인 원소의 번호, 최소인 원소의 번호
arr.argmax(), arr[1].argmax(), arr.argmin(), arr[1].argmin()

(7, 3, 0, 0)

In [26]:
# 특정 축(차원)으로 덧셈 수행하기
arr.sum(axis=0), arr.sum(axis=1)

(array([11, 13, 15, 17]), array([10, 46]))

In [27]:
# Indexing + Slicing + Aggregation 응용
arr[1].min(), arr[1][2:].sum()

(10, 25)

### numpy 기본 4. 고급 Broadcasting

In [28]:
arr1 = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
arr2 = np.array([[0,1,2],[0,1,2],[0,1,2],[0,1,2]])
arr1.shape, arr2.shape

((4, 3), (4, 3))

In [29]:
arr1 + arr2          # (4x3)  +  (4x3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [30]:
arr1 + np.array([0,1,2])     # (4x3) + (1x3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [31]:
#  (4x1) + (1x3)
np.array([[0],[10],[20],[30]]) + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])